### PR TITLE
Add option to scroll by line number

### PR DESCRIPTION
**Pull request by juliaanvaneijndt**

### CODE REVIEW

**Comment by georgebrindeiro-vtex** [comment]
@juliaanvaneijndt does this pull request add scrolling by line number to the original scrolling by content functionality, or does it replace it? If it's the former, I'll gladly accept it. 

Otherwise, I would have to ask you to do some extra work so that no functionality is lost. If you aren't up to it, I'll try to work on it on the next couple weeks.

**Comment by juliaanvaneijndt** [comment]
@georgebrindeiro Congrats! 
Glad to see this moving on: yes, this PR is and addition to the original package. I put an option in the settings to switch between content and line-number syncing. Sorry, I should have said something about it in the issue section.

**Comment by IRobL** [comment]
Thanks for sharing this @juliaanvaneijndt!  I'm kinda new to atom plugins, how can I install this from your git repo's src?  Do you have your work published as a package somewhere?

**Comment by juliaanvaneijndt** [comment]
@IRobL quite easy: download from https://github.com/juliaanvaneijndt/scroll-sync unzip in ~/.atom/packages/
or better directly `apm install juliaanvaneijndt/scroll-sync`

@georgebrindeiro, are you still maintaining the package? it'll be great if this PR was merged.

**Pull request merged**
